### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by thelong1EU** [nbsp-team/MaterialFilePicker#49]
I so that you use the GPL 2.0 licence. I want to use my app commercially. Can you use Apache?

**Comment by lukaville** [comment]
Hi! Now we are using Apache 2.0 license :)  🎉

**Comment by thelong1EU** [comment]
Thanks. Love you.

**Comment by jpventura** [comment]
@long1eu, @lukaville once a code is licensed under GPLv2.0, you are not allowed to relicense it under Apache 2.0 because it is considered a derivative work.

According to the [Apache Software Foundation](http://www.apache.org/licenses/GPL-compatibility.html), _static linking to a GPLv2 library it is considered by the GPLv2 authors to create a derivative work._

**Comment by long1eu** [comment]
Hi!

Thank so much for your work, but I don't think I'm using your library
anymore.
